# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "gridlock"
version = "0.4.0"
entrypoint = "src/gridlock.typ"
authors = ["ssotoen"]
license = "Unlicense"
description = "Grid typesetting in Typst"
repository = "https://github.com/ssotoen/gridlock"
keywords = ["grid"]
categories = [
  "layout",
  "book",
  "paper",
]
# disciplines = []
compiler = "0.13.0"
exclude = [ "docs", ]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
